name: edu_sound_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  noise_meter: ^5.0.1  # DB 측정기용
  permission_handler: ^11.3.1
  flutter_recorder: ^1.1.2  # 주파수 분석용
  fl_chart: ^0.66.2  # 차트 라이브러리

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
